import { ITaxInfo } from './taxInfo';

export interface IInvoiceDetail {
  _id: string;
  _assetId: string;
  startDate: string;
  endDate: string;
  pricePerDay: number;
  tripDays: number;
  ownerEarning: number;
  discount: number;
  deposit: number;
  taxInfo: ITaxInfo[];
  totalPrice: number;
  _bookingId: string;
  _quotationId: string;
  invoiceStatus: number;
  displayStatus: string;
  insurancePerDay: number;
  isInsuranceIncluded: boolean;
  totalInsurance: number;
  tripAmount: number;
  __v: number;
  _depositPaymentCardId: string;
  _rentPaymentCardId: string;
  rewardPointsApplied: number;
  rewardPointRate: number;
  discountPercentage: number;
  taxOnOwnerEarningPct: number;
  taxOnOwnerEarning: number;
  platformComission: number;
  platformComissionPct: number;
  vatOnOwnerEarningPct: number;
  vatOnOwnerEarning: number;
  promoDiscount: number;
  promoCode: string;
  originalPerDayPrice: number;
  numberOfAssets: number;
  pickNDropsCount: number;
  rewardDisc: number;

  chargeOnDeposit: number;
  createdOn: string;
  invoiceType: string;
  isInsuranceRequired: boolean;
  ownerEarningBeforeTaxes: number;
  ownerTypeCode: string;
  paymentGatewayShare: number;
  paymentGatewaySharePct: number;
  paymentMode: number;
  promoCodeAdditionalData: string;
  renterTypeCode: string;
  selectedInsuranceTypeCode: string;
  serviceFee: number;
  totalAppliedDiscount: number;
  totalDue: number;
  totalPaid: number;
  totalRemaining: number;
  updatedOn: string;
  vatOnChargeOnDeposit: number;
  vatOnCommission: number;
  vatOnCommissionPct: number;
  vatOnInsurance: number;
  vatOnPaymentGatewayShare: number;
  vatOnPaymentGatewaySharePct: number;
  vatOnRent: number;
  vatOnRentPct: number;
  whtOnCommission: number;
  whtOnCommissionPct: number;
  whtOnPaymentGatewayShare: number;
  whtOnPaymentGatewaySharePct: number;
  whtOnRent: number;
  whtOnRentPct: number;
  platformDiscount: number;

}

export class InvoiceDetail implements IInvoiceDetail {
  _id = '';
  _assetId = '';
  startDate = '';
  endDate = '';
  pricePerDay = 0;
  tripDays = 0;
  ownerEarning = 0;
  discount = 0;
  deposit = 0;
  taxInfo = [];
  totalPrice = 0;
  _bookingId = '';
  _quotationId = '';
  invoiceStatus = 0;
  displayStatus = '';
  insurancePerDay = 0;
  isInsuranceIncluded = false;
  totalInsurance = 0;
  tripAmount = 0;
  __v = 0;
  _depositPaymentCardId = '';
  _rentPaymentCardId = '';
  rewardPointsApplied = 0;
  rewardPointRate = 0;
  discountPercentage = 0;
  taxOnOwnerEarningPct = 0;
  taxOnOwnerEarning = 0;
  platformComission = 0;
  platformComissionPct = 0;
  vatOnOwnerEarningPct = 0;
  vatOnOwnerEarning = 0;
  promoDiscount = 0;
  promoCode = '';
  originalPerDayPrice = 0;
  numberOfAssets = 0;
  pickNDropsCount = 0;
  rewardDisc = 0;


  chargeOnDeposit: number;
  createdOn: string;
  invoiceType: string;
  isInsuranceRequired: boolean;
  ownerEarningBeforeTaxes: number;
  ownerTypeCode: string;
  paymentGatewayShare: number;
  paymentGatewaySharePct: number;
  paymentMode: number;
  promoCodeAdditionalData: string;
  renterTypeCode: string;
  selectedInsuranceTypeCode: string;
  serviceFee: number;
  totalAppliedDiscount: number;
  totalDue: number;
  totalPaid: number;
  totalRemaining: number;
  updatedOn: string;
  vatOnChargeOnDeposit: number;
  vatOnCommission: number;
  vatOnCommissionPct: number;
  vatOnInsurance: number;
  vatOnPaymentGatewayShare: number;
  vatOnPaymentGatewaySharePct: number;
  vatOnRent: number;
  vatOnRentPct: number;
  whtOnCommission: number;
  whtOnCommissionPct: number;
  whtOnPaymentGatewayShare: number;
  whtOnPaymentGatewaySharePct: number;
  whtOnRent: number;
  whtOnRentPct: number;
  platformDiscount = 0;
}
