import { IKeyValue } from './key-value';

export interface ICreateAssetSpecs {
    _id: string;
    _makeId: string;
    makeName: string;
    _modelId: string;
    assetModelName: string;
    _subModelId: string;
    subModelName: string;
    modelYear: number;
    numberOfSeats: number;
    numberOfDoors: number;
    isAutomaticTransmission: boolean;
    fuelTypes: IKeyValue[];
    mileage: number;
    gpsTypeCode: string;
    gpsTypeDisplayName: string;
    driverSpokenLanguages: IKeyValue[];
    colorCode: string;
    colorDisplayName: string;
    assetTypeCode: string;
    assetTypeDisplayName: string;
    description: string;
    features: IKeyValue[];
    rentalCategoryCode: string;
    rentalCategoryDisplayName: string;
    ownerTypeCode: string;
    ownerTypeDisplayName: string;
    isInsuranceRequired: boolean;
    isUnlist: boolean;
    isActive: boolean;
    agreedTermsAndConditionsCopy: string;
    numberOfBaggages: number;
}
export class CreateAssetSpecs implements ICreateAssetSpecs {
    '_id': string;
    '_makeId' = '';
    makeName = '';
    '_modelId' = '';
    assetModelName = '';
    '_subModelId' = '';
    subModelName = '';
    modelYear = 0;
    numberOfSeats = 0;
    numberOfDoors = 0;
    isAutomaticTransmission = true;
    fuelTypes = [];
    mileage = 0;
    gpsTypeCode = '';
    gpsTypeDisplayName = '';
    driverSpokenLanguages = [];
    colorCode = '';
    colorDisplayName = '';
    assetTypeCode = '';
    assetTypeDisplayName = '';
    description = '';
    features = [];
    rentalCategoryCode = '';
    rentalCategoryDisplayName = '';
    ownerTypeCode = '';
    ownerTypeDisplayName = '';
    isInsuranceRequired = false;
    isUnlist = false;
    isActive = true;
    agreedTermsAndConditionsCopy = '';
    ownerName = '';
    numberOfBaggages = 0;
}
